name: active-analysis-main

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ubuntu dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run:
        sudo -E apt-get install --fix-missing -qq -o Acquire::Retries=3
        libvips-tools
        imagemagick
        ffmpeg
        poppler-utils

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
        bundler-cache: true

    - name: Run the default task
      run: bundle exec rake
